/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Matches: () => import('#controllers/matches_controller'),
  Mcp: () => import('#controllers/mcp_controller'),
}
