/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/ally.ts" />
/// <reference path="../../config/app.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/bodyparser.ts" />
/// <reference path="../../config/cors.ts" />
/// <reference path="../../config/database.ts" />
/// <reference path="../../config/encryption.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/session.ts" />
/// <reference path="../../config/redis.ts" />
/// <reference path="../../config/shield.ts" />
