/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthIdentitySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'emailVerified',
    'id',
    'lastUsedAt',
    'passwordHash',
    'provider',
    'providerProfile',
    'providerSubject',
    'updatedAt',
    'userId',
  ] as const
  $columns = AuthIdentitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare emailVerified: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare passwordHash: string | null
  @column()
  declare provider: string
  @column()
  declare providerProfile: any | null
  @column()
  declare providerSubject: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class MatchCommandSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'matchId',
    'playerSlot',
    'tick',
    'toolInput',
    'toolName',
    'toolOutput',
  ] as const
  $columns = MatchCommandSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare matchId: string
  @column()
  declare playerSlot: number
  @column()
  declare tick: number
  @column()
  declare toolInput: any
  @column()
  declare toolName: string
  @column()
  declare toolOutput: any | null
}

export class MatchPlayerSchema extends BaseModel {
  static $columns = [
    'agentToken',
    'createdAt',
    'displayName',
    'finalEnergy',
    'finalScore',
    'finalUnits',
    'id',
    'isConnected',
    'matchId',
    'modelId',
    'playerType',
    'slot',
    'updatedAt',
    'userId',
  ] as const
  $columns = MatchPlayerSchema.$columns
  @column()
  declare agentToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column()
  declare finalEnergy: number | null
  @column()
  declare finalScore: number | null
  @column()
  declare finalUnits: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isConnected: boolean
  @column()
  declare matchId: string
  @column()
  declare modelId: string | null
  @column()
  declare playerType: string
  @column()
  declare slot: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class MatchSnapshotSchema extends BaseModel {
  static $columns = ['createdAt', 'gameState', 'id', 'matchId', 'tick'] as const
  $columns = MatchSnapshotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare gameState: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare matchId: string
  @column()
  declare tick: number
}

export class MatchSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'currentTick',
    'finishedAt',
    'id',
    'mapConfig',
    'maxPlayers',
    'maxTicks',
    'startedAt',
    'status',
    'tickRate',
    'updatedAt',
    'winnerSlot',
  ] as const
  $columns = MatchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare currentTick: number
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mapConfig: any
  @column()
  declare maxPlayers: number
  @column()
  declare maxTicks: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare tickRate: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerSlot: number | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'avatarUrl',
    'createdAt',
    'fullName',
    'id',
    'isActive',
    'lastLoginAt',
    'systemRole',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare systemRole: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
